redirects:
  - from: "/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FYeDKCMfkPjihliTK8OIW%2Fuploads%2F5kRioKxkonwifTUqwR9d%2FLYOPAY%20Ecosystem%20Product%20Deck.pptx.pdf"
    to: "https://files.gitbook.com/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FpHWR2Wn6kSrORXTppHba%2Fuploads%2FEsTw8UjJ9eGGqKtSfqjU%2FLYOTRADE%20Product%20Deck.pdf"
    code: 301
  - from: "/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FW4sUF29Mx8prLkJM7pJP%2Fuploads%2FsGKciOe2mly8VxSJo0e2%2FLYOPAY%20Ecosystem%20Product%20Deck.pptx%20(1).pdf"
    to: "https://files.gitbook.com/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FpHWR2Wn6kSrORXTppHba%2Fuploads%2FEsTw8UjJ9eGGqKtSfqjU%2FLYOTRADE%20Product%20Deck.pdf"
    code: 301
